pipeline {
    agent any

    tools {
        maven 'Maven' // Specify your Maven installation name in Jenkins
        jdk 'JDK11'   // Specify the JDK installation name in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
}

